# Generated by Django 5.2.4 on 2025-08-08 15:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Blog',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='blog',
        ),
    ]
